# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

LABEL io.k8s.description="Apache httpd child image" \
      io.k8s.display-name="Apache httpd child image" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="httpd, apache"

#RUN yum install -y rubygems && yum clean all -y
RUN sed -i 's/Listen 80/Listen 8080/g' /etc/httpd/conf/httpd.conf && \
    sed -i 's/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g' /etc/httpd/conf/httpd.conf && \
		chgrp -R 0 /var/log/httpd /var/run/httpd && \
		chmod -R g=u /var/log/httpd /var/run/httpd

USER 1001

EXPOSE 8080
